[package]
name = "bin"
version = "0.1.0"
authors = ["Brendan Hansknecht <brendan.hansknecht@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_a = { path = "../lib_a" }
lib_b = { path = "../lib_b" }
log = "0.4"